In [1]:
#pip install numpy

In [2]:
#pip install pandas

In [3]:
#pip install matplotlib

In [4]:
#pip install scikit-learn

In [2]:
import numpy as nump
import pandas as pd
import matplotlib.pyplot as py
from sklearn.impute import SimpleImputer
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
%matplotlib inline


In [3]:
import warnings
warnings.simplefilter('ignore')

In [4]:
data=pd.read_csv('Salary_dataset.csv')
data

Unnamed: 0  YearsExperience    Salary
0            0              1.2   39344.0
1            1              1.4   46206.0
2            2              1.6   37732.0
3            3              2.1   43526.0
4            4              2.3   39892.0
5            5              3.0   56643.0
6            6              3.1   60151.0
7            7              3.3   54446.0
8            8              3.3   64446.0
9            9              3.8   57190.0
10          10              4.0   63219.0
11          11              4.1   55795.0
12          12              4.1   56958.0
13          13              4.2   57082.0
14          14              4.6   61112.0
15          15              5.0   67939.0
16          16              5.2   66030.0
17          17              5.4   83089.0
18          18              6.0   81364.0
19          19              6.1   93941.0
20          20              6.9   91739.0
21          21              7.2   98274.0
22          22              8.0  101303.0
23          23              8.3  113813.0
24          24              8.8  109432.0
25          25              9.1  105583.0
26          26              9.6  116970.0
27          27              9.7  112636.0
28          28             10.4  122392.0
29          29             10.6  121873.0

In [5]:
dataset=data.drop(['Unnamed: 0'],axis=1)
dataset

YearsExperience    Salary
0               1.2   39344.0
1               1.4   46206.0
2               1.6   37732.0
3               2.1   43526.0
4               2.3   39892.0
5               3.0   56643.0
6               3.1   60151.0
7               3.3   54446.0
8               3.3   64446.0
9               3.8   57190.0
10              4.0   63219.0
11              4.1   55795.0
12              4.1   56958.0
13              4.2   57082.0
14              4.6   61112.0
15              5.0   67939.0
16              5.2   66030.0
17              5.4   83089.0
18              6.0   81364.0
19              6.1   93941.0
20              6.9   91739.0
21              7.2   98274.0
22              8.0  101303.0
23              8.3  113813.0
24              8.8  109432.0
25              9.1  105583.0
26              9.6  116970.0
27              9.7  112636.0
28             10.4  122392.0
29             10.6  121873.0

In [6]:
x=dataset.iloc[:,0].values.reshape(-1,1)
y=dataset.iloc[:,1].values.reshape(-1,1)

In [7]:
x

array([[ 1.2],
       [ 1.4],
       [ 1.6],
       [ 2.1],
       [ 2.3],
       [ 3. ],
       [ 3.1],
       [ 3.3],
       [ 3.3],
       [ 3.8],
       [ 4. ],
       [ 4.1],
       [ 4.1],
       [ 4.2],
       [ 4.6],
       [ 5. ],
       [ 5.2],
       [ 5.4],
       [ 6. ],
       [ 6.1],
       [ 6.9],
       [ 7.2],
       [ 8. ],
       [ 8.3],
       [ 8.8],
       [ 9.1],
       [ 9.6],
       [ 9.7],
       [10.4],
       [10.6]])

In [8]:
y

array([[ 39344.],
       [ 46206.],
       [ 37732.],
       [ 43526.],
       [ 39892.],
       [ 56643.],
       [ 60151.],
       [ 54446.],
       [ 64446.],
       [ 57190.],
       [ 63219.],
       [ 55795.],
       [ 56958.],
       [ 57082.],
       [ 61112.],
       [ 67939.],
       [ 66030.],
       [ 83089.],
       [ 81364.],
       [ 93941.],
       [ 91739.],
       [ 98274.],
       [101303.],
       [113813.],
       [109432.],
       [105583.],
       [116970.],
       [112636.],
       [122392.],
       [121873.]])

In [9]:
#from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=0)

In [10]:
x_train

array([[ 9.7],
       [ 4.1],
       [ 5.4],
       [ 8. ],
       [ 3. ],
       [ 5.2],
       [ 3.3],
       [ 4.6],
       [ 8.3],
       [ 6.9],
       [ 1.4],
       [10.6],
       [ 3.1],
       [ 2.3],
       [ 6. ],
       [ 6.1],
       [ 3.8],
       [ 3.3],
       [ 9.1],
       [ 2.1],
       [ 1.2],
       [ 7.2],
       [ 5. ],
       [ 4.1]])

In [11]:
x_test

array([[ 1.6],
       [10.4],
       [ 4.2],
       [ 4. ],
       [ 9.6],
       [ 8.8]])

In [12]:
y_train

array([[112636.],
       [ 55795.],
       [ 83089.],
       [101303.],
       [ 56643.],
       [ 66030.],
       [ 64446.],
       [ 61112.],
       [113813.],
       [ 91739.],
       [ 46206.],
       [121873.],
       [ 60151.],
       [ 39892.],
       [ 81364.],
       [ 93941.],
       [ 57190.],
       [ 54446.],
       [105583.],
       [ 43526.],
       [ 39344.],
       [ 98274.],
       [ 67939.],
       [ 56958.]])

In [13]:
y_test

array([[ 37732.],
       [122392.],
       [ 57082.],
       [ 63219.],
       [116970.],
       [109432.]])

In [14]:
#from sklearn.linear_model import LinearRegression
lm=LinearRegression()

In [15]:
lm.fit(x_train,y_train)

LinearRegression()

In [16]:
predictvalue=lm.predict(x_test)

In [17]:
predictvalue

array([[ 40749.96184072],
       [122700.62295594],
       [ 64962.65717022],
       [ 63100.14214487],
       [115250.56285456],
       [107800.50275317]])

In [18]:
compare=pd.DataFrame(x_test,columns=['CGPA'])

In [19]:
compare["AVLDATA"]=y_test
compare['Predictdata']=predictvalue

In [20]:
compare

CGPA   AVLDATA    Predictdata
0   1.6   37732.0   40749.961841
1  10.4  122392.0  122700.622956
2   4.2   57082.0   64962.657170
3   4.0   63219.0   63100.142145
4   9.6  116970.0  115250.562855
5   8.8  109432.0  107800.502753

In [21]:
from sklearn.metrics import mean_squared_error,mean_absolute_error,r2_score

In [22]:
mean_squared_error(y_test,predictvalue)

12823412.298126565

In [23]:
mean_absolute_error(y_test,predictvalue)

2446.17236904651

In [24]:
r2_score(y_test,predictvalue)

0.988169515729126